# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Artwork.destroy_all
Department.destroy_all

Department.create(name: "European Paintings")
Department.create(name: "Medieval Art")
Department.create(name: "Modern and Contemporary Art")
Department.create(name: "The American Wing")
Department.create(name: "Asian Art")
Department.create(name: "Greek and Roman Art")

Artwork.create(api_id: 437979, image_url: "https://images.metmuseum.org/CRDImages/ep/original/ep1975.280.2.bw.R.jpg", department_id: Department.first.id)
Artwork.create(api_id: 437532, image_url: "https://images.metmuseum.org/CRDImages/ep/original/DP-14286-003.jpg", department_id: Department.first.id)
Artwork.create(api_id: 435882, image_url: "https://images.metmuseum.org/CRDImages/ep/original/DT47.jpg", department_id: Department.first.id)
Artwork.create(api_id: 436435, image_url: "https://images.metmuseum.org/CRDImages/ep/original/DP169214.jpg", department_id: Department.first.id)
Artwork.create(api_id: 438817, image_url: "https://images.metmuseum.org/CRDImages/ep/original/DT46.jpg", department_id: Department.first.id)
Artwork.create(api_id: 436535, image_url: "https://images.metmuseum.org/CRDImages/ep/original/DT1567.jpg", department_id: Department.first.id)
Artwork.create(api_id: 437127, image_url: "https://i.pinimg.com/originals/02/96/e3/0296e37e14d61e3076cbe5d7e5a014e7.jpg", department_id: Department.first.id)
Artwork.create(api_id: 437835, image_url: "https://images.metmuseum.org/CRDImages/ep/original/DT1500.jpg", department_id: Department.first.id)
Artwork.create(api_id: 438821, image_url: "https://images.metmuseum.org/CRDImages/ep/original/DT1025.jpg", department_id: Department.first.id)
Artwork.create(api_id: 436892, image_url: "https://images.metmuseum.org/CRDImages/ep/original/DP243637.jpg", department_id: Department.first.id)
Artwork.create(api_id: 466580, image_url: "https://images.metmuseum.org/CRDImages/ep/original/DP-12954-001.jpg", department_id: Department.second.id)
Artwork.create(api_id: 465991, image_url: "https://images.metmuseum.org/CRDImages/md/original/DT127.jpg", department_id: Department.second.id)
Artwork.create(api_id: 464156, image_url: "https://images.metmuseum.org/CRDImages/md/original/DP102289.jpg", department_id: Department.second.id)
Artwork.create(api_id: 466645, image_url: "https://images.metmuseum.org/CRDImages/md/original/DP325825.jpg", department_id: Department.second.id)
Artwork.create(api_id: 464142, image_url: "https://images.metmuseum.org/CRDImages/md/original/DT142.jpg", department_id: Department.second.id)
Artwork.create(api_id: 470298, image_url: "https://images.metmuseum.org/CRDImages/md/original/DT107.jpg", department_id: Department.second.id)
Artwork.create(api_id: 467594, image_url: "https://images.metmuseum.org/CRDImages/md/original/DP144070.jpg", department_id: Department.second.id)
Artwork.create(api_id: 464483, image_url: "https://images.metmuseum.org/CRDImages/md/original/DT128.jpg", department_id: Department.second.id)
Artwork.create(api_id: 464333, image_url: "https://images.metmuseum.org/CRDImages/md/original/DP134383.jpg", department_id: Department.second.id)
Artwork.create(api_id: 488486, image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Portrait_of_a_German_Officer%2C_Marsden_Hartley.jpg/300px-Portrait_of_a_German_Officer%2C_Marsden_Hartley.jpg", department_id: Department.third.id)
Artwork.create(api_id: 488570, image_url: "https://c1.staticflickr.com/5/4384/23572933648_e31cf9ccfa_b.jpg", department_id: Department.third.id)
Artwork.create(api_id: 488978, image_url: "https://www.jackson-pollock.org/images/paintings/autumn-rhythm.jpg", department_id: Department.third.id)
Artwork.create(api_id: 490036, image_url: "http://res.cloudinary.com/culturemap-com/image/upload/q_auto/ar_4:3,c_fill,g_faces:center,w_1200/v1536344618/photos/281239_original.jpg", department_id: Department.third.id)
Artwork.create(api_id: 482133, image_url: "http://lichtensteinpaintings.com/Stepping%20Out%20Roy%20Lichtenstein.jpg", department_id: Department.third.id)
Artwork.create(api_id: 488319, image_url: "http://canvasprintshere.com/uploadpic/wassily_kandinsky/big/improvisation_no_27_the_garden_of_love_c_1912.jpg", department_id: Department.third.id)
Artwork.create(api_id: 486270, image_url: "https://c1.staticflickr.com/5/4132/5159428806_b935d56eee.jpg", department_id: Department.third.id)
Artwork.create(api_id: 488694, image_url: "https://www.georgiaokeeffe.net/images/paintings/cows-skull-red-white-and-blue.jpg", department_id: Department.third.id)
Artwork.create(api_id: 486162, image_url: "https://upload.wikimedia.org/wikipedia/en/8/8d/Pablo_Picasso%2C_1905%2C_Au_Lapin_Agile_%28At_the_Lapin_Agile%29%2C_oil_on_canvas%2C_99.1_x_100.3_cm%2C_Metropolitan_Museum_of_Art.jpg", department_id: Department.third.id)
Artwork.create(api_id: 483038, image_url: "https://images.curiator.com/images/t_l/art/bxoy2fx4jmjv0gsqlzv0/red-grooms-chance-encounter-at-3-a-m.jpg", department_id: Department.third.id)
Artwork.create(api_id: 10154, image_url: "https://images.metmuseum.org/CRDImages/ad/original/DT82.jpg", department_id: Department.fourth.id)
Artwork.create(api_id: 12550, image_url: "https://upload.wikimedia.org/wikipedia/commons/8/8d/Autumn_MET_189875.jpg", department_id: Department.fourth.id)
Artwork.create(api_id: 10497, image_url: "https://images.metmuseum.org/CRDImages/ad/original/DP-12550-001.jpg", department_id: Department.fourth.id)
Artwork.create(api_id: 13763, image_url: "https://media.wsimag.com/attachments/5dd304393373d46a24754b9d8730342b0a89b429/store/fill/545/307/013abf8f9d96f53d8cbd49be5a43be17b34655eac1cd02ebd3e695eae0e4/Sally-Miller-American-Litchfield-Connecticut-Memorial-painting-ca-1811-Watercolor-and-ink-on.jpg", department_id: Department.fourth.id)
Artwork.create(api_id: 11417, image_url: "https://images.metmuseum.org/CRDImages/ad/original/DP215410.jpg", department_id: Department.fourth.id)
Artwork.create(api_id: 14871, image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Childe_Hassam_The_Water_Garden_1909.jpg/640px-Childe_Hassam_The_Water_Garden_1909.jpg", department_id: Department.fourth.id)
Artwork.create(api_id: 11227, image_url: "https://images.metmuseum.org/CRDImages/ad/original/ap87.8.8.jpg", department_id: Department.fourth.id)
Artwork.create(api_id: 11055, image_url: "https://images.metmuseum.org/CRDImages/ad/original/DT2051.jpg", department_id: Department.fourth.id)
Artwork.create(api_id: 11234, image_url: "https://images.metmuseum.org/CRDImages/ad/original/DT98.jpg", department_id: Department.fourth.id)
Artwork.create(api_id: 40081, image_url: "https://images.metmuseum.org/CRDImages/as/original/DP273822.jpg", department_id: Department.fifth.id)
Artwork.create(api_id: 44858, image_url: "https://images.metmuseum.org/CRDImages/as/original/DT229.jpg", department_id: Department.fifth.id)
Artwork.create(api_id: 44918, image_url: "https://images.metmuseum.org/CRDImages/as/original/DT1615.jpg", department_id: Department.fifth.id)
Artwork.create(api_id: 38341, image_url: "https://images.metmuseum.org/CRDImages/as/original/DT5236.jpg", department_id: Department.fifth.id)
Artwork.create(api_id: 39936, image_url: "https://www.lazerhorse.org/wp-content/uploads/2014/08/Emperor-Huizong-Finches-and-Bamboo.jpg", department_id: Department.fifth.id)
Artwork.create(api_id: 37145, image_url: "https://images.metmuseum.org/CRDImages/as/original/DP119525.jpg", department_id: Department.fifth.id)
Artwork.create(api_id: 49156, image_url: "https://images.metmuseum.org/CRDImages/as/original/DP105303_CRD.jpg", department_id: Department.fifth.id)
Artwork.create(api_id: 56353, image_url: "https://images.metmuseum.org/CRDImages/as/original/DP141067.jpg", department_id: Department.fifth.id)
Artwork.create(api_id: 38198, image_url: "https://images.metmuseum.org/CRDImages/as/original/DT237.jpg", department_id: Department.fifth.id)
Artwork.create(api_id: 39666, image_url: "https://images.metmuseum.org/CRDImages/as/original/DT5083.jpg", department_id: Department.fifth.id)
Artwork.create(api_id: 254649, image_url: "https://images.metmuseum.org/CRDImages/gr/original/DT282.jpg", department_id: Department.last.id)
Artwork.create(api_id: 248579, image_url: "https://images.metmuseum.org/CRDImages/gr/original/DP-14287-137retry.jpg", department_id: Department.last.id)
Artwork.create(api_id: 248851, image_url: "https://images.metmuseum.org/CRDImages/gr/original/DP337262.jpg", department_id: Department.last.id)
Artwork.create(api_id: 247008, image_url: "https://images.metmuseum.org/CRDImages/gr/original/DP141474.jpg", department_id: Department.last.id)
Artwork.create(api_id: 250551, image_url: "https://images.metmuseum.org/CRDImages/gr/original/DP218568.jpg", department_id: Department.last.id)
Artwork.create(api_id: 250939, image_url: "https://images.metmuseum.org/CRDImages/gr/original/DP146610.jpg", department_id: Department.last.id)
Artwork.create(api_id: 256403, image_url: "https://images.metmuseum.org/CRDImages/gr/original/DP222664.jpg", department_id: Department.last.id)
Artwork.create(api_id: 247415, image_url: "https://images.metmuseum.org/CRDImages/gr/original/DP252926.jpg", department_id: Department.last.id)
Artwork.create(api_id: 247009, image_url: "https://images.metmuseum.org/CRDImages/gr/original/DP105943.jpg", department_id: Department.last.id)
Artwork.create(api_id: 248140, image_url: "https://images.metmuseum.org/CRDImages/gr/original/DT10909.jpg", department_id: Department.last.id)